### PR TITLE
set drv to NULL on dispose

### PR DESCRIPTION
**Pull request by naveedhd**
Sets driver pointer to NULL in `disposeDriver` after calling `delete`.

### CODE REVIEW

**Comment by naveedhd** [comment]
@stonier FYI

**Comment by kintzhao** [comment]
Is there any error happens without set drv=NULL? @naveedhd

**Comment by stonier** [comment]
no error, but @naveedhd you should probably why and how you use the sdk

**Comment by naveedhd** [comment]
@kintzhao In our nodelet implementation, we have recovery logic for re-initializing driver if:

1) not properly initialized on init
2) `checkRPLidarHealth` returns error [nodelet #185-188](https://github.com/yujinrobot/rplidar_ros/blob/devel/src/rplidar_nodelet.cpp#L185-L188)

So for NULL checking and safety, this should be pointed to NULL after deletion.

**Pull request closed without merging**
