### PR TITLE
Include catkin directories

### PR DESCRIPTION
**Pull request by stonier**
Without this, it won't build without sourcing setup.bash first (which is not a necessary step).

Note that this will mean it fails the first time you try to release
it as a deb on the osrf build farm as it is a sandboxed environment.

### CODE REVIEW

**Comment by stonier** [comment]
Also added a more convenient launcher arg configuration for users of the library.

**Comment by ipa-mig** [comment]
@stonier did you add the Eclipse files (`.cproject`, `.project` and the `.settings` directory) on purpose? They contains at least the `YUJIN_WORKSPACE` variable...

**Comment by stonier** [comment]
@ipa-mig no, this PR was supposed to be only the first commit. Didn't expect to have the team working continually on this branch. I'll close this one and create pull requests individually.

**Comment by stonier** [comment]
New PR with just the catkin fix in #16

**Pull request closed without merging**
